spring:
  # redis 配置
  redis:
#    host: 175.24.111.52
#    port: 5268
    host: 192.168.1.100
    port: 6379
    password: root
    timeout: 20s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
